ALTER TABLE ws_services ADD COLUMN inspection_id INT DEFAULT NULL;
ALTER TABLE ws_services ADD COLUMN description TEXT DEFAULT NULL;
ALTER TABLE ws_services ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;